// Game state
let currentScene = 0;
let scenes = [
    {
        background: 'assets/backgrounds/outside_school.png',
        character: '',
        characterName: 'Narrator',
        dialog: 'It\'s a beautiful spring morning at Sakura High School. The cherry blossoms are in full bloom, marking the beginning of a new school year.'
    },
    {
        background: 'assets/backgrounds/classroom.png',
        character: 'assets/characters/mei.png',
        characterPosition: 'left',
        characterName: 'Mei',
        dialog: 'Hi! I\'m Mei Tanaka. I\'m new here, and today is my first day at Sakura High!'
    },
    {
        background: 'assets/backgrounds/classroom.png',
        character: 'assets/characters/mei.png',
        characterPosition: 'left',
        characterName: 'Mei',
        dialog: 'I wonder what kind of adventures await me here...'
    },
    {
        background: 'assets/backgrounds/classroom.png',
        character: 'assets/characters/yuki.png',
        characterPosition: 'right',
        characterName: '???',
        dialog: 'Hey there! You must be the new student everyone\'s talking about!'
    },
    {
        background: 'assets/backgrounds/classroom.png',
        character: 'assets/characters/yuki.png',
        characterPosition: 'right',
        characterName: 'Yuki',
        dialog: 'I\'m Yuki Sato, the class representative. Welcome to Sakura High!'
    },
    {
        background: 'assets/backgrounds/classroom.png',
        character: '',
        characterName: 'Narrator',
        dialog: '...and that\'s how Mei met Yuki.'
    },
    {
        background: 'assets/backgrounds/classroom.png',
        character: '',
        characterName: 'Developer',
        dialog: 'Such a cliché story, right?'
    },
    {
        background: 'assets/backgrounds/classroom.png',
        character: 'assets/characters/developer.png',
        characterName: 'Developer',
        dialog: 'But regardless, I\'m impressed this was all generated by AI and a text-to-image model.'
    },
    {
        background: 'assets/backgrounds/classroom.png',
        character: 'assets/characters/developer.png',
        characterName: 'Developer',
        dialog: '"I\'m not sure if I should be proud or sad." -> this is the line Claude is suggesting as a good follow-up, which I find hillarious.'
    },
    {
        background: 'assets/backgrounds/classroom.png',
        character: 'assets/characters/developer.png',
        characterName: 'Developer',
        dialog: 'I decided to make this to practice using AI and seeing how quickly I could make a very simple visual novel game thing. This was a 2 hour exercise, give or take. Not too bad, right?'
    },
    {
        background: 'assets/backgrounds/classroom.png',
        character: 'assets/characters/developer.png',
        characterName: 'Developer',
        dialog: 'You can see the chat transcript and more information in the README.md file. Bye!'
    },
    // These are follow-up scenes Claude suggested
    // {
    //     background: 'assets/backgrounds/classroom.png',
    //     character: '',
    //     characterName: 'Narrator',
    //     dialog: 'Mei and Yuki quickly became friends, and together they explored the school and its secrets.'
    // },
    // {
    //     background: 'assets/backgrounds/classroom.png',
    //     character: '',
    //     characterName: 'Narrator',
    //     dialog: 'As they spent more time together, they discovered a hidden room in the school library.'
    // },
    // {
    //     background: 'assets/backgrounds/classroom.png',
    //     character: '',
    //     characterName: 'Narrator',
    //     dialog: 'They found a mysterious book that seemed to be a map to a secret passage.'
    // },
    // {
    //     background: 'assets/backgrounds/classroom.png',
    //     character: '',
    //     characterName: 'Narrator',
    //     dialog: 'The passage led them to a hidden garden filled with cherry blossoms.'
    // },
];

// DOM elements
const backgroundElement = document.getElementById('background');
const characterElement = document.getElementById('character');
const characterNameElement = document.getElementById('character-name');
const dialogTextElement = document.getElementById('dialog-text');
const nextButton = document.getElementById('next-button');

// Initialize the game
function initGame() {
    // Set default background for empty scenes
    backgroundElement.onerror = () => {
        console.warn('Background image failed to load:', backgroundElement.src);
        backgroundElement.src = 'assets/backgrounds/classroom.png';  // Use classroom as fallback
    };
    
    // Set default character for empty scenes
    characterElement.onerror = () => {
        console.warn('Character image failed to load:', characterElement.src);
        characterElement.style.display = 'none';
    };
    
    // Preload images
    preloadImages();
    
    updateScene();
}

// Preload all images to ensure smooth transitions
function preloadImages() {
    const images = new Set();
    scenes.forEach(scene => {
        if (scene.background) images.add(scene.background);
        if (scene.character) images.add(scene.character);
    });
    
    images.forEach(src => {
        const img = new Image();
        img.src = src;
    });
}

// Update the scene based on current scene index
function updateScene() {
    const scene = scenes[currentScene];
    const previousScene = currentScene > 0 ? scenes[currentScene - 1] : null;
    
    // Only fade background if it's changing
    const isBackgroundChanging = previousScene && previousScene.background !== scene.background;
    if (isBackgroundChanging) {
        backgroundElement.style.opacity = '0';
    }
    
    // Only fade character if it's changing
    const isCharacterChanging = previousScene && previousScene.character !== scene.character;
    if (isCharacterChanging) {
        characterElement.style.opacity = '0';
    }
    
    // Update background if provided
    if (scene.background) {
        setTimeout(() => {
            backgroundElement.src = scene.background;
            backgroundElement.style.opacity = '1';
        }, isBackgroundChanging ? 300 : 0);
    }
    
    // Update character if provided
    if (scene.character) {
        setTimeout(() => {
            characterElement.style.display = 'block';
            characterElement.src = scene.character;
            // Update character position
            characterElement.className = scene.characterPosition ? `position-${scene.characterPosition}` : 'position-center';
            characterElement.style.opacity = '1';
        }, isCharacterChanging ? 300 : 0);
    } else {
        characterElement.style.display = 'none';
    }
    
    // Update character name and dialog
    characterNameElement.textContent = scene.characterName;
    dialogTextElement.textContent = scene.dialog;
}

// Handle next button click
nextButton.addEventListener('click', () => {
    if (currentScene < scenes.length - 1) {
        currentScene++;
        updateScene();
    }
});

// Start the game when the page loads
window.addEventListener('load', initGame); 